// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetClientVersion():Promise<models.AppVersionInfo>;

export function GetDashboard():Promise<models.CenterDashboardData>;

export function GetFrpcConfig(arg1:string):Promise<models.FrpcConfigData>;

export function GetHomeStats():Promise<models.HomeStatsData>;

export function GetNodes():Promise<models.NodeListData>;

export function GetRunnerData(arg1:number):Promise<models.RunnerData>;

export function GetRunnerRuntimeStatus():Promise<models.RunnerRuntimeStatus>;

export function GetTrafficDaily(arg1:number):Promise<models.DailyTrafficResponse>;

export function GetTrafficTunnels(arg1:number):Promise<models.TrafficTunnelData>;

export function GetTunnelsOverview(arg1:number,arg2:number,arg3:number):Promise<models.TunnelOverviewData>;

export function GetUserInfo():Promise<models.UserInfoData>;

export function GetUserTrafficStats():Promise<models.UserTrafficData>;

export function GetUserTunnels(arg1:number,arg2:number):Promise<models.TunnelListData>;

export function StartRunner(arg1:string):Promise<models.RunnerRuntimeStatus>;

export function StopRunner():Promise<models.RunnerRuntimeStatus>;
