// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClientVersion() {
  return window['go']['services']['CenterService']['GetClientVersion']();
}

export function GetDashboard() {
  return window['go']['services']['CenterService']['GetDashboard']();
}

export function GetFrpcConfig(arg1) {
  return window['go']['services']['CenterService']['GetFrpcConfig'](arg1);
}

export function GetHomeStats() {
  return window['go']['services']['CenterService']['GetHomeStats']();
}

export function GetNodes() {
  return window['go']['services']['CenterService']['GetNodes']();
}

export function GetRunnerData(arg1) {
  return window['go']['services']['CenterService']['GetRunnerData'](arg1);
}

export function GetRunnerRuntimeStatus() {
  return window['go']['services']['CenterService']['GetRunnerRuntimeStatus']();
}

export function GetTrafficDaily(arg1) {
  return window['go']['services']['CenterService']['GetTrafficDaily'](arg1);
}

export function GetTrafficTunnels(arg1) {
  return window['go']['services']['CenterService']['GetTrafficTunnels'](arg1);
}

export function GetTunnelsOverview(arg1, arg2, arg3) {
  return window['go']['services']['CenterService']['GetTunnelsOverview'](arg1, arg2, arg3);
}

export function GetUserInfo() {
  return window['go']['services']['CenterService']['GetUserInfo']();
}

export function GetUserTrafficStats() {
  return window['go']['services']['CenterService']['GetUserTrafficStats']();
}

export function GetUserTunnels(arg1, arg2) {
  return window['go']['services']['CenterService']['GetUserTunnels'](arg1, arg2);
}

export function StartRunner(arg1) {
  return window['go']['services']['CenterService']['StartRunner'](arg1);
}

export function StopRunner() {
  return window['go']['services']['CenterService']['StopRunner']();
}
