// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFrpcStatus() {
  return window['go']['services']['FrpcService']['GetFrpcStatus']();
}

export function GetGitHubMirrorURL() {
  return window['go']['services']['FrpcService']['GetGitHubMirrorURL']();
}

export function InstallOrUpdateFrpc() {
  return window['go']['services']['FrpcService']['InstallOrUpdateFrpc']();
}

export function RemoveFrpc() {
  return window['go']['services']['FrpcService']['RemoveFrpc']();
}

export function SetGitHubMirrorURL(arg1) {
  return window['go']['services']['FrpcService']['SetGitHubMirrorURL'](arg1);
}
