// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginOAuthLogin(arg1, arg2) {
  return window['go']['services']['TokenService']['BeginOAuthLogin'](arg1, arg2);
}

export function ClearOAuthToken() {
  return window['go']['services']['TokenService']['ClearOAuthToken']();
}

export function HasOAuthToken() {
  return window['go']['services']['TokenService']['HasOAuthToken']();
}
