// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginOAuthLogin():Promise<boolean>;

export function ClearOAuthToken():Promise<void>;

export function HasOAuthToken():Promise<boolean>;
